[book]
authors  = ["Randy Halim"]
language = "en"
src      = "src-build"
title    = "Randy's Cyber Survival Guide"

# [preprocessor.obsidian]
[preprocessor.indexing]

[output.html]

[output.pdf]
generate-document-outline = true
display-header-footer     = true
header-template           = "<h3 style='font-size:8px; margin-left: 48%' class='title'></h3>"
footer-template           = "<p style='font-size:10px; margin-left: 48%'><span class='pageNumber'></span> / <span class='totalPages'></span></p>"

